apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "tomcat-sample-app", "namespace": "",
      "kind": "DeploymentConfig"}]'
  creationTimestamp: null
  labels:
    name: tomcat-sample-app
  name: tomcat-sample-pipeline
spec:
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: "Git"
    git:
      uri: "https://github.com/nstrug/tomcat-docker"
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: "Jenkinsfile"
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
status:
  lastVersion: 0
